# Generated by Django 2.2.14 on 2020-07-06 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0002_load_initial_data"),
    ]

    operations = [
        migrations.AddField(
            model_name="customtext",
            name="jhgjhgf",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="customtext",
            name="jhgjhtjg",
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="customtext",
            name="kjyuiuyiuy",
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
